### ISSUE TITLE
slave-java提供的maven是否可以使用阿里的仓库

### ISSUE THREAD

**Issue by SoyMeng** [AliyunContainerService/jenkins-slaves#8]
slave-java提供的maven是否可以使用阿里的仓库?

**Comment by denverdino** [comment]
@ringtail fyi https://yq.aliyun.com/articles/65274

**Comment by ringtail** [comment]
@SoyMeng 可以的，slave-java提供的是java与maven的运行时环境，您希望使用阿里的仓库我理解主要是希望能够提高构建的速度，从这个出发点来讲，可以从如下几个方面来优化：
1.在pom中修改registry mirror的信息为阿里云的镜像仓库   
2.优化Dockerfile缓存maven构建cache    
3.挂载.m2可以使用本地的仓库    
可以参考上面的文章地址：https://yq.aliyun.com/articles/65274
